version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/php-apache.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./api.php:/var/www/html/api.php
      - ./assets:/var/www/html/assets
      - ./app/src:/var/www/html/src
    depends_on:
      - db
    networks:
      - devnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/seed/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - devnet

networks:
  devnet:

volumes:
  db_data:
