name: Setup Database

on:
  workflow_dispatch:

jobs:
  setup-db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for MySQL to be ready
      run: sleep 20

    - name: Create and seed database
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS appdb;"
        mysql -h 127.0.0.1 -u root -proot appdb < seed.sql
